=== mgmgsrtm/projet_sudoku/sudoku_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="sudoku" type="SudokuType"/>

    <!-- pour la grille -->
    <xsd:complexType name="SudokuType">
        <xsd:sequence>
            <xsd:element name="row" type="RowType" minOccurs="9" maxOccurs="9"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- pour une ligne -->
    <xsd:complexType name="RowType">
        <xsd:sequence>
            <xsd:element name="cell" type="CellType" minOccurs="9" maxOccurs="9"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- pour une cellule -->
    <xsd:complexType name="CellType">
        <!-- "v" - valeur (1-9 ou vide) -->
        <xsd:attribute name="v" type="CellValueType" use="optional"/>
        
        <!-- "fixed" - donnée initiale, par défaut false -->
        <xsd:attribute name="fixed" type="xsd:boolean" use="optional" default="false"/>
    </xsd:complexType>

    <!-- type simple, de 1 à 9 -->
    <xsd:simpleType name="CellValueType">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="9"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== mgmgsrtm/projet_sudoku/grille_valeur_invalide.xml
<?xml version="1.0" encoding="UTF-8"?>
<sudoku xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="sudoku_schema.xsd">
    
    <!-- valeur 10 invalide -->
    <row>
        <cell v="5" fixed="true"/>
        <cell v="3" fixed="true"/>
        <cell/>
        <cell v="10"/>  <!-- 10 n'est pas entre 1 et 9 -->
        <cell v="7" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
    </row>
    
    <row>
        <cell v="6" fixed="true"/>
        <cell/>
        <cell/>
        <cell v="1" fixed="true"/>
        <cell v="9" fixed="true"/>
        <cell v="5" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
    </row>
    
    <row>
        <cell/>
        <cell v="9" fixed="true"/>
        <cell v="8" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell v="6" fixed="true"/>
        <cell/>
    </row>
    
    <row>
        <cell v="8" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell v="6" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell v="3" fixed="true"/>
    </row>
    
    <row>
        <cell v="4" fixed="true"/>
        <cell/>
        <cell/>
        <cell v="8" fixed="true"/>
        <cell/>
        <cell v="3" fixed="true"/>
        <cell/>
        <cell/>
        <cell v="1" fixed="true"/>
    </row>
    
    <row>
        <cell v="7" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell v="2" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell v="6" fixed="true"/>
    </row>
    
    <row>
        <cell/>
        <cell v="6" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell v="2" fixed="true"/>
        <cell v="8" fixed="true"/>
        <cell/>
    </row>
    
    <row>
        <cell/>
        <cell/>
        <cell/>
        <cell v="4" fixed="true"/>
        <cell v="1" fixed="true"/>
        <cell v="9" fixed="true"/>
        <cell/>
        <cell/>
        <cell v="5" fixed="true"/>
    </row>
    
    <row>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell v="8" fixed="true"/>
        <cell/>
        <cell/>
        <cell v="7" fixed="true"/>
        <cell v="9" fixed="true"/>
    </row>
    
</sudoku>

=== mgmgsrtm/projet_sudoku/grille_simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<sudoku xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="sudoku_schema.xsd">
    <row>
        <cell v="5" fixed="true"/>
        <cell v="3" fixed="true"/>
        <cell/>
        <cell v="7" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
    </row>
    <row>
        <cell v="6" fixed="true"/>
        <cell/>
        <cell v="1" fixed="true"/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
    </row>
    <row>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
        <cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
</sudoku>

=== mgmgsrtm/projet_sudoku/grille_gagnante.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- complÃ¨tement et correctement remplie -->
<sudoku xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="sudoku_schema.xsd">
    
    <!-- Ligne 1 -->
    <row>
        <cell v="8" fixed="true"/>
        <cell v="1"/>
        <cell v="3"/>
        <cell v="9"/>
        <cell v="2"/>
        <cell v="5"/>
        <cell v="7"/>
        <cell v="4"/>
        <cell v="6"/>
    </row>
    
    <!-- Ligne 2 -->
    <row>
        <cell v="9"/>
        <cell v="5"/>
        <cell v="6"/>
        <cell v="8"/>
        <cell v="4"/>
        <cell v="7"/>
        <cell v="3"/>
        <cell v="1"/>
        <cell v="2"/>
    </row>
    
    <row>
        <cell v="4"/>
        <cell v="7"/>
        <cell v="2"/>
        <cell v="3"/>
        <cell v="6"/>
        <cell v="1"/>
        <cell v="8"/>
        <cell v="9"/>
        <cell v="5"/>
    </row>
    
    <row>
        <cell v="6"/>
        <cell v="2"/>
        <cell v="4"/>
        <cell v="7"/>
        <cell v="1"/>
        <cell v="9"/>
        <cell v="5"/>
        <cell v="3"/>
        <cell v="8"/>
    </row>
    
    <row>
        <cell v="7"/>
        <cell v="9"/>
        <cell v="5"/>
        <cell v="6"/>
        <cell v="3"/>
        <cell v="8"/>
        <cell v="4"/>
        <cell v="2"/>
        <cell v="1"/>
    </row>
    
    <row>
        <cell v="3"/>
        <cell v="8"/>
        <cell v="1"/>
        <cell v="4"/>
        <cell v="5"/>
        <cell v="2"/>
        <cell v="9"/>
        <cell v="6"/>
        <cell v="7"/>
    </row>
    
    <row>
        <cell v="2"/>
        <cell v="3"/>
        <cell v="8"/>
        <cell v="1"/>
        <cell v="7"/>
        <cell v="4"/>
        <cell v="6"/>
        <cell v="5"/>
        <cell v="9"/>
    </row>
    
    <row>
        <cell v="5"/>
        <cell v="4"/>
        <cell v="9"/>
        <cell v="2"/>
        <cell v="8"/>
        <cell v="6"/>
        <cell v="1"/>
        <cell v="7"/>
        <cell v="3"/>
    </row>
    
    <row>
        <cell v="1"/>
        <cell v="6"/>
        <cell v="7"/>
        <cell v="5"/>
        <cell v="9"/>
        <cell v="3"/>
        <cell v="2"/>
        <cell v="8"/>
        <cell v="4"/>
    </row>
    
</sudoku>

=== mgmgsrtm/projet_sudoku/grille_vide.xml
<?xml version="1.0" encoding="UTF-8"?>
<sudoku xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="sudoku_schema.xsd">
    
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    <row>
        <cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/><cell/>
    </row>
    
</sudoku>
